### PR TITLE
Swagger description updates

### PR DESCRIPTION
**Pull request by dalebremner**
@RackHD/corecommitters @srinia6 @keedya @BillyAbildgaard

### CODE REVIEW

**Comment by yyscamper** [comment]
The github complains "527 additions, 603 deletions not shown because the diff is too large. Please use a local Git client to view these changes.", could you please summary what change you did for this PR?

**Comment by BillyAbildgaard** [comment]
basically all Dale did here was go through the YAML and update the descriptions of the different routes to be more informative when needed.  We had a barebones description prior to this.

**Comment by anhou** [comment]
it seems have to use 'wget https://github.com/RackHD/on-http/pull/380.patch' to download for local review

**Comment by yyscamper** [comment]
Interesting, The first time I find the github refuses to display the diff. @dalebremner @BillyAbildgaard I will download it to local and review it tomorrow.

**Comment by benbp** [comment]
@yyscamper yeah I get the same thing. I think it may be because of how large the swagger file itself is? So even though the changelist is relatively small, the total diff size is large.

**Comment by keedya** [comment]
Looks good @dalebremner :+1:

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
