### PR TITLE
Run a single workflow with an array of nodeIds for tag generation

### PR DESCRIPTION
**Pull request by benbp**
Requires https://github.com/RackHD/on-tasks/pull/320 and https://github.com/RackHD/on-taskgraph/pull/162 (interdependent).

@RackHD/corecommitters @heckj @pscharla

### CODE REVIEW

**Comment by changev** [comment]
jenkins: depends on https://github.com/RackHD/on-taskgraph/pull/162 https://github.com/RackHD/on-tasks/pull/320

**Comment by changev** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
Interdependent PRs test: http://10.240.19.21/job/Maglev-BRI-Test/job/on-multi/93/

RackHD log file: http://10.240.19.21/job/Maglev-BRI-Test/job/on-multi/93/artifact/build/vagrant.log

```
2:12:47 PM http.1 |      - Error: Task.Catalog.GenerateTag: JSON schema validation failed - data.nodeIds should be array
2:12:47 PM http.1 |      -     at TaskOptionValidator.JsonSchemaValidator.validatePatternsSkipped (/home/vagrant/src/on-http/node_modules/on-core/lib/common/json-schema-validator.js:94:23)
2:12:47 PM http.1 |      -     at TaskOptionValidator.validateContextSkipped (/home/vagrant/src/on-http/node_modules/on-tasks/lib/utils/task-option-validator.js:61:21)
2:12:47 PM http.1 |      -     at /home/vagrant/src/on-http/node_modules/on-tasks/lib/task.js:434:31
2:12:47 PM http.1 |      -     at bound (domain.js:287:14)
2:12:47 PM http.1 |      -     at runBound (domain.js:300:12)
2:12:47 PM http.1 |      -     at tryCatcher (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/util.js:26:23)
2:12:47 PM http.1 |      -     at Promise._settlePromiseFromHandler (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:507:31)
2:12:47 PM http.1 |      -     at Promise._settlePromiseAt (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:581:18)
2:12:47 PM http.1 |      -     at Promise._settlePromises (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/promise.js:697:14)
2:12:47 PM http.1 |      -     at Async._drainQueue (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:123:16)
2:12:47 PM http.1 |      -     at Async._drainQueues (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:133:10)
2:12:47 PM http.1 |      -     at Immediate.Async.drainQueues [as _onImmediate] (/home/vagrant/src/on-http/node_modules/on-core/node_modules/bluebird/js/main/async.js:15:14)
2:12:47 PM http.1 |      -     at processImmediate [as _immediateCallback] (timers.js:383:17)
2:12:47 PM http.1 |    message:   Task.Catalog.GenerateTag: JSON schema validation failed - data.nodeIds should be array
```

**Comment by anhou** [comment]
👍

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Pull request merged**
