### PR TITLE
Remove postLookup() logic, and fix the failure of installing Esxi when setting static IP.

### PR DESCRIPTION
**Pull request by lanchongyizu**
The solution is
- wget callbackScript into directory /tmp in %pre
- then move it to /vmfs/volumes/datastore1 in %post
- then copy the content into /etc/rc.local.d/local.sh

@RackHD/corecommitters @panpan0000 @keedya

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by keedya** [comment]
@lanchongyizu I m not sure ssh validation will pass in this case. I probably missed something here?

**Comment by yyscamper** [comment]
@lanchongyizu : could you please explain why this can solve the static IP issue?

**Comment by lanchongyizu** [comment]
@keedya For now, ssh validation fails for all OSes, so it is not caused by this PR.
@yyscamper Because callbackScript is `wget` in `%pre` where static IP is not set then.

**Comment by panpan0000** [comment]
:+0: :-)  looks good.  just questions:  (1) so in %pre, the "/vmfs/volumes/datastore1" has not been established or is not accessible ?    (2) can you help: why wget works in %pre  but not in %firstboot ?

**Comment by lanchongyizu** [comment]
@panpan0000 
(1) yes, it's not established
(2) `wget` in `%firstboot` will fail since setting static IP makes `lookups` fail  when pulling callbackScript.

**Comment by keedya** [comment]
@lanchongyizu it  is :-1: for me. If lookup table is not updated, ssh validation will fail.

**Comment by lanchongyizu** [comment]
@keedya When the last notification is posted, static IP will be in ARP cache, so it is in lookup table.

**Comment by yyscamper** [comment]
My comment purely depends on the test result. I eagerly to remove the "ugly" code to POST lookup in ESXi kickstart file, if the testing is OK, this is definitely :+1:

**Comment by lanchongyizu** [comment]
Since the issue https://github.com/RackHD/RackHD/issues/467 exists, we can't remove postLookups() currently.

**Comment by lanchongyizu** [comment]
This has been solved by https://github.com/RackHD/on-http/pull/531, so close the PR.

**Pull request closed without merging**
