### PR TITLE
InstallCoreOS: Add Vault support for Ignition, boot args support via GRUB

### PR DESCRIPTION
**Pull request by tgelter**
This PR is for two small additions to the CoreOS install task:
* You can now use ignition data stored in Hashicorp Vault
* You can now specify extra kernel boot parameters for GRUB to include
depends on: https://github.com/RackHD/on-tasks/pull/494

### CODE REVIEW

**Comment by keedya** [comment]
ok to test

**Comment by keedya** [comment]
Adding more people to review:
@hohene @gpaulos @geoff-reid

**Comment by tgelter** [comment]
Please note that with this PR, the behavior of Ignition/cloud-init has intentionally been changed.
CoreOS has deprecated the use of cloud-init (https://coreos.com/os/docs/1492.4.0/provisioning.html) in favor of Ignition. Previously, RackHD has applied both Ignition data as well as cloud-init userdata. With this PR, that behavior changes. If an ignition config is specified, the RackHD cloud-init won't be applied.

**Comment by keedya** [comment]
Added https://rackhd.atlassian.net/browse/RAC-5964 to update our functional tests

**Pull request merged**
