### PR TITLE
updating GET node/{id} client lib

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
creating new `get node` reference for client libraries to get identifier of a node

@RackHD/veyron

### CODE REVIEW

**Comment by dalebremner** [comment]
jenkins, test this please

**Comment by dalebremner** [comment]
jenkins, test this please

**Comment by amymullins** [comment]
Reference RAC issue: https://rackhd.atlassian.net/browse/RAC-5217

**Comment by BillyAbildgaard** [comment]
jenkins, test this please

**Pull request merged**
