### PR TITLE
Fixed KVM installation for RHEL 7 and CentOS 7

### PR DESCRIPTION
**Pull request by derrickostertag**
Added installation packages to install KVM for RHEL 7 and CentOS 7 in kickstart file.

### CODE REVIEW

**Comment by heckj** [comment]
@derrickostertag good with this, but did you need this in the 1.1 branch as well?

**Comment by derrickostertag** [comment]
@RackHD/corecommitters

**Comment by derrickostertag** [comment]
Yes, I have one for 1.1 as well

**Comment by heckj** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
^^ unrelated coverage failure

+1

**Comment by derrickostertag** [comment]
Thanks!

**Pull request merged**
