### PR TITLE
Add local copy of swagger_router fitting

### PR DESCRIPTION
**Pull request by zyoung51**
A change to swagger-node-runner (https://github.com/theganyo/swagger-node-runner/
commit/5cc5df13f0b880b1b42350e1f1d914978b066820) has not been packaged upstream
yet.  This commit makes the change locally and should be removed once the updated 
swagger-node-runner package is included into swagger-express-mw.

### CODE REVIEW

**Comment by zyoung51** [comment]
@RackHD/corecommitters @tannoa2 @uppalk1 @keedya @geoff-reid @dalebremner

**Comment by brianparry** [comment]
:+1: Looks good.  I would like to somehow record that this is temporary fitting that we'll use until a swagger-node-runner release with your change is published to npm.  Maybe open an issue?

**Comment by zyoung51** [comment]
@brianparry I did note that this should be removed once the swagger-node-runner is updated in the commit mesage.

**Comment by brianparry** [comment]
@zyoung51 I see it in the commit message now.  Thanks!

**Comment by jlongever** [comment]
+1 

Assuming the coverage decrease is due to adding temporary code without testing it?

**Comment by keedya** [comment]
:+1:

**Pull request merged**
