### PR TITLE
RAC-5241 Can't perform node rediscovery using post /workflows O

### PR DESCRIPTION
**Pull request by manfrednde**
This PR is to remove the graph length( 0 or 1) check( so that we have able to execute a graph that have a graph within it. 
The rediscovery graph length is 2 and it will fail with the check is place.

### CODE REVIEW

**Comment by manfrednde** [comment]
@stuart-stanley 
@linlynn 
@anhou

**Comment by panpan0000** [comment]
test this please

**Comment by manfrednde** [comment]
@jimturnquist Please take a look

**Comment by jimturnquist** [comment]
All good.  Coverage decrease is minimal.

**Pull request merged**
