### PR TITLE
Clean jshint errors

### PR DESCRIPTION
**Pull request by anhou**
clean all the jshint errors for on-http

vagrant@rackhd-demo:~/src/on-http$ ./node_modules/.bin/jshint -c .jshintrc lib index.js || true
lib/api/1.1/northbound/nodes.js: line 33, col 5, 'Errors' is defined but never used.

lib/api/2.0/nodes.js: line 9, col 44, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 13, col 58, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 17, col 45, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 21, col 47, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 25, col 45, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 29, col 48, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 33, col 65, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 37, col 51, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 41, col 52, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 45, col 58, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 50, col 52, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 54, col 53, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 63, col 101, Line is too long.
lib/api/2.0/nodes.js: line 58, col 70, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 67, col 59, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 71, col 59, 'res' is defined but never used.

lib/api/2.0/pollers.js: line 39, col 50, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 51, col 43, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 70, col 45, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 102, col 60, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 121, col 45, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 140, col 50, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 159, col 51, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 178, col 62, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 197, col 47, 'res' is defined but never used.
lib/api/2.0/pollers.js: line 216, col 54, 'res' is defined but never used.

lib/api/redfish-1.0/chassis.js: line 186, col 20, ['sensorType'] is better written in dot notation.
lib/api/redfish-1.0/chassis.js: line 189, col 20, ['sensorType'] is better written in dot notation.
lib/api/redfish-1.0/chassis.js: line 221, col 20, ['sensorType'] is better written in dot notation.
lib/api/redfish-1.0/chassis.js: line 224, col 20, ['sensorReadingUnits'] is better written in dot notation.

lib/api/redfish-1.0/service-root.js: line 5, col 105, Line is too long.

lib/api/redfish-1.0/systems.js: line 10, col 5, Redefinition of 'Promise'.
lib/api/redfish-1.0/systems.js: line 11, col 5, Redefinition of '_'.
lib/api/redfish-1.0/systems.js: line 420, col undefined, Identifier 'reset_type' is not in camel case.
lib/api/redfish-1.0/systems.js: line 424, col undefined, Identifier 'reset_type' is not in camel case.
lib/api/redfish-1.0/systems.js: line 9, col 5, 'Errors' is defined but never used.

lib/fittings/json_error_handler.js: line 7, col undefined, Identifier 'error_handler' is not in camel case.
lib/fittings/json_error_handler.js: line 6, col 46, 'bagpipes' is defined but never used.
lib/fittings/json_error_handler.js: line 6, col 34, 'fittingDef' is defined but never used.

lib/fittings/swagger_render.js: line 9, col undefined, Identifier 'swagger_render' is not in camel case.
lib/fittings/swagger_render.js: line 18, col 101, Line is too long.
lib/fittings/swagger_render.js: line 7, col 46, 'bagpipes' is defined but never used.

lib/fittings/swagger_serdes.js: line 4, col 5, Redefinition of '_'.

44 errors
vagrant@rackhd-demo:~/src/on-http$

### CODE REVIEW

**Comment by yyscamper** [comment]
Wondering why there is coverage lost since you just commit some style change.

**Comment by heckj** [comment]
@yyscamper -0.004% is in my mind a rounding error, and not worth digging on, but given that some of this lint cleanup was *removing* lines that weren't used, the total number of lines that are being analyzed will change, which would impact the coverage numbers.

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
@heckj , yes no worth to dig it out, just a little curious.

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
