### PR TITLE
Remove temporary swagger-node-runner workaround

### PR DESCRIPTION
**Pull request by zyoung51**
- swagger-node-runner has been updated to 0.6.15 which contains
  the multiple controllersDirs fix

### CODE REVIEW

**Comment by zyoung51** [comment]
@RackHD/corecommitters @uppalk1 @keedya @tannoa2 @brianparry

**Comment by brianparry** [comment]
:+1:

**Comment by jlongever** [comment]
+1

**Comment by benbp** [comment]
:+1:

**Pull request merged**
