### PR TITLE
Nodes view clean-up

### PR DESCRIPTION
**Pull request by srinia6**
Add links, and new fields for easy navigation. @dalebremner @keedya @BillyAbildgaard @RackHD/corecommitters

### CODE REVIEW

**Comment by keedya** [comment]
@jlongever

**Comment by srinia6** [comment]
test this please

**Comment by keedya** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
FYI @VulpesArtificem

**Pull request merged**
