### PR TITLE
Add alerts when SSDP services are added or removed.

### PR DESCRIPTION
**Pull request by brianparry**
* Add node-cache dependency.
* Handlers for cache delete, set, and expire events
* Set cache entries based on M-SEARCH response.

@RackHD/corecommitters

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by keedya** [comment]
:+1:

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by benbp** [comment]
I don't have an issue with adding the cache dependency here, but just an FYI we do already include https://www.npmjs.com/package/lru-cache in our dependencies, albeit it has some slightly different behavior (maxAge vs. ttl, dispose callbacks but no way to trigger callbacks on `set` like node-cache does).

**Comment by brianparry** [comment]
@benbp I attempted to switch to lru-cache but I had issues with it prematurely expiring entries.  If you don't object, I'd like to stick with node-cache for now.

**Comment by benbp** [comment]
+1

**Pull request merged**
