### PR TITLE
RAC-5913 fix bad URI in taskservice

### PR DESCRIPTION
**Pull request by gpaulos**
Removed elements in URI that were failing validator.

Paired with Derrick

@derrickostertag @jimturnquist

### CODE REVIEW

**Comment by jimturnquist** [comment]
Dependent change is in.

**Comment by jimturnquist** [comment]
Test this please

**Comment by jimturnquist** [comment]
Test this please.

**Comment by gpaulos** [comment]
test this please

**Comment by derrickostertag** [comment]
@jimturnquist

**Pull request merged**
