### PR TITLE
Feature/2.0 catalogs view

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
added view for catalogs and updated unit test.

Also, felt compelled to fix a few jshint errors I saw in a few other files too...

@RackHD/corecommitters @srinia6 @keedya @dalebremner

### CODE REVIEW

**Comment by srinia6** [comment]
+1

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by BillyAbildgaard** [comment]
test this please

**Pull request merged**
