### PR TITLE
adding more options support in CoreOS yaml

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
updating coreOS yaml to be able to template options passed in via the body.

@srinia6 @dalebremner @keedya @tannoa2 @geoff-reid @uppalk1

### CODE REVIEW

**Comment by BillyAbildgaard** [comment]
depends on https://github.com/RackHD/on-tasks/pull/373

**Comment by tannoa2** [comment]
+1

**Comment by cgx027** [comment]
:+1:

**Comment by BillyAbildgaard** [comment]
@RackHD/corecommitters just need a CC review to get merged whenever someone gets a chance

**Comment by dalebremner** [comment]
+1

**Pull request merged**
