### PR TITLE
added redactions to workflows GET by :id

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@RackHD/corecommitters 

New way to resolve: https://github.com/RackHD/RackHD/issues/241
This PR depends on: https://github.com/RackHD/on-core/pull/228
both PRs resolve: https://github.com/RackHD/RackHD/issues/417

this is the final PR to revert old (complex and overlapping) encryption of passwords to simply redact secret fields prior to the object being passed to the client.

### CODE REVIEW

**Comment by cgx027** [comment]
:100:

**Comment by tldavies** [comment]
👍  once it is rerun and passes tests with the dependent PR

**Comment by benbp** [comment]
👍

**Comment by DavidjohnBlodgett** [comment]
@brianparry if you get the chance could you review this?

once the build issues with on-core are resolved, this will address masking secrets on specific api paths that a github issue was raised.

**Comment by DavidjohnBlodgett** [comment]
test this please

**Comment by DavidjohnBlodgett** [comment]
@RackHD/corecommitters this should be merge ready.

**Pull request merged**
