### PR TITLE
Cleanup of 2.0 API schemas

### PR DESCRIPTION
**Pull request by brianparry**
* Clear additionalProperties for all schemas.
* Add tags property to nodes schema
* Change unit tests to abide by new schema rules.

### CODE REVIEW

**Comment by brianparry** [comment]
@keedya @dalebremner @srinia6 @BillyAbildgaard

**Comment by yyscamper** [comment]
:+1:

**Comment by keedya** [comment]
:+1:

**Comment by keedya** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Pull request merged**
