### PR TITLE
Fix incorrect wget argument in esxi kickstart file

### PR DESCRIPTION
**Pull request by zyoung51**
/usr/bin/wget --spider results in an "unrecognized option '--spider'"
error in ESXi 5.5 and ESXi 6.0.  Change the command option to the correct
"-s" argument

### CODE REVIEW

**Comment by anhou** [comment]
:+1:  just curious about previous behavior, does this issue exist before, and still could work with this error?

**Comment by zyoung51** [comment]
@anhou The previous command never worked but nothing was dependent on it working, so the error went unnoticed.

**Comment by anhou** [comment]
@zyoung51 Gotta, Thanks!

**Comment by zyoung51** [comment]
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @jlongever

**Pull request merged**
