### PR TITLE
Support partitioning for CentOS installation

### PR DESCRIPTION
**Pull request by anhou**
temporarily only support CentOS, CentOS is a starting point, other Linux OS will be added. 
more description, please see docs PR: https://github.com/RackHD/docs/pull/278
related PR: https://github.com/RackHD/on-tasks/pull/213

also address ODR-654 https://hwjiraprd01.corp.emc.com/browse/ODR-654

@RackHD/corecommitters @RackHD/rackhd_dev

### CODE REVIEW

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
+1

**Comment by WangWinson** [comment]
:+1:

**Pull request merged**
