### PR TITLE
[redfish] Add Redfish authentication

### PR DESCRIPTION
**Pull request by zyoung51**
- Enable Basic authentication and token authentication as required for
  Redfish v1.0
- Enable Session Service:
  POST: /SessionService/Sessions to login
  GET: /SessionService/Sessions to query current sessions
  DELETE: /SessionService/Sessions/:id to logout

@RackHD/corecommitters @uppalk1 @keedya @tannoa2

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
+1

**Comment by keedya** [comment]
:+1:

**Comment by uppalk1** [comment]
:+1:

**Pull request merged**
