### PR TITLE
Add post Lookup functionality back to esxi ks

### PR DESCRIPTION
**Pull request by keedya**
@brianparry @zyoung51 @RackHD/corecommitters @amymullins @jlongever @tannoa2 @uppalk1 
@yyscamper @lanchongyizu 
resolves https://github.com/RackHD/RackHD/issues/420

### CODE REVIEW

**Comment by tannoa2** [comment]
+1

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by uppalk1** [comment]
+1

**Comment by lanchongyizu** [comment]
:+1:

**Pull request merged**
