### PR TITLE
Modify files/:filename/latest to return the latest file

### PR DESCRIPTION
**Pull request by iceiilin**
Fix ODR-605 about "Web UI / POST BIOSImage / API not selecting latest image with same basename uploaded for install". 
Metadata array got from on-http file service is in the time order based on waterline mechanism. Change waterline find method to return the list in sorted manner.

### CODE REVIEW

**Comment by pengz1** [comment]
+1

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by iceiilin** [comment]
test this please

**Comment by iceiilin** [comment]
This Jenkins error is generated in API 2.0 workflow tests. I will leave it to @dalebremner for triage.
For this PR, I checked the code repo, and it didn't touch API 2.0 code. It is ready to be merged.

**Comment by benbp** [comment]
@VulpesArtificem please review.

**Comment by iceiilin** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by iceiilin** [comment]
To fix the P1 ODR, change the solution to keep the file in the default order and only return the last item in the file array, so that it can pass Jenkins test. I have created a issue in https://github.com/RackHD/on-http/issues/229 to track the previous failure.

**Pull request merged**
