### PR TITLE
add NTP configuration in esx-ks

### PR DESCRIPTION
**Pull request by lanchongyizu**
**Fix ODR-750** NTP configuration in esx-ks

The solution is adding ntpSevers options to support NTP configuration, so that the users could use the private NTP servers if needed.

@RackHD/corecommitters @panpan0000 

rackhd/on-tasks#259

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by panpan0000** [comment]
@RackHD/corecommitters , can somebody merge this , since two :+1 already received ?

**Comment by benbp** [comment]
@panpan0000 @lanchongyizu I believe there may be a conflict/CI build that has to be resolved on the dependent PR before I can merge this (https://github.com/RackHD/on-tasks/pull/259#issuecomment-229657535, related to upstream changes)?

**Comment by panpan0000** [comment]
test this please

**Pull request merged**
