### PR TITLE
Modify  brocade catalog script

### PR DESCRIPTION
**Pull request by dpasupathi**
Change the catalog script according to sku definition change done in on-skupack PR#28

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by brianparry** [comment]
ok to test

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by yyscamper** [comment]
@dpasupathi : could you please add some sample data so that we are aware of why you change the index.

**Comment by brianparry** [comment]
test this please

**Comment by dpasupathi** [comment]
@yyscamper :  Thanks for reviewing the changes. I noticed that i had merged my local changes properly. Now i had modified the file properly.  Please ignore my first changes. 

The changes here i made is to change the catalog information for brocade switch.  Earlier the catalog information i collected was not specific and it might conflict with other vendors. Hence I had modified the SKU definition and the corresponding catalog information. 
Please refer the pull request https://github.com/RackHD/on-skupack/pull/28  for more details.

**Comment by benbp** [comment]
👍

**Pull request merged**
