### PR TITLE
Fix ODR869: Rename graph options 'osName' for Esx to ESXi in Redfish BootImage API

### PR DESCRIPTION
**Pull request by yyscamper**
Fix [ODR869](https://hwjiraprd01.corp.emc.com/browse/ODR-869) and take this chance to fix an outstanding rename work that stated in this issue: https://github.com/RackHD/RackHD/issues/218

@RackHD/corecommitters @gpaulos @cgx027 @pengz1 @iceiilin @WangWinson 

Jenkins: depends on https://github.com/RackHD/on-tasks/pull/333

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by iceiilin** [comment]
:+1:

**Comment by yyscamper** [comment]
As @changev replied in  https://github.com/RackHD/on-tasks/pull/333, the Jenkins-Dependency-PR failure is not a problem for this PR itself, there is something wrong for the jenkins result reporting.

**Pull request merged**
