### PR TITLE
Better init script

### PR DESCRIPTION
**Pull request by ytjohn**
- enable start/stop/restart and pid monitoring
 - put logs in /var/log/rackhd

https://github.com/RackHD/on-http/issues/416

### CODE REVIEW

**Comment by ytjohn** [comment]
Hold up on this - still has issues relating to background task. Might implement start-stop-daemon.

**Comment by ytjohn** [comment]
Upgraded script to use start-stop-daemon.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
+0.
I tried to read and learn , but sorry know little about this area :-P
just curious , is it common practice  in debian services that use a pid file , to ensure single service instance ?

**Comment by ytjohn** [comment]
@panpan0000 Yes, there would be one master process. If it's something like Apache httpd or nginx, there will be the master process and it will handle spawning its own threads.  Of course, those are server processes and will fork/detach on their own. nodejs is not really designed that way, and it only knows how to run in foreground. 

Systems like upstart and systemd handle non-forking processes, assigning them a pid and running them in the background. With init scripts, you have to utilize a program to fork the foreground process (nodejs).  Debian and Redhat provide "start-stop-daemon" to handle just that.  

Sometimes popular programming languages will promote another tool. In python, the most popular is [supervisord](http://supervisord.org/). For nodejs, the most popular appears to something call [forever](https://github.com/foreverjs/forever). If I can, I try to avoid these because they're not included with existing distributions. supervisord has been around longer and does have debian/rpm packages available, so I would go with that over foreverjs. Foreverjs is only installable via npm.  But start-stop-daemon has been around forever.

The best solution would be to write upstart and systemd files, and setup post-install file in the debian package to determine which file to install based on the os version.

**Comment by jimturnquist** [comment]
I loaded this on an appliance running RackHD and verified that start/start/restart are working well.

+1

**Comment by ytjohn** [comment]
I did a bit more looking, and I realized I should add exit levels.  Let me push up a commit that includes those.

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html

**Comment by jimturnquist** [comment]
@ytjohn Which exit statuses are you proposing?  Your change already supports 0 and 3 (Running and Stopped).  Which other states are you considering.

When on-http is running:

onrack@ora:~$ sudo systemctl status on-http
● on-http.service - LSB: on-http
   Loaded: loaded (/etc/init.d/on-http; bad; vendor preset: enabled)
   Active: active (running) since Mon 2016-08-29 20:24:27 UTC; 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1881 ExecStop=/etc/init.d/on-http stop (code=exited, status=0/SUCCESS)
  Process: 1976 ExecStart=/etc/init.d/on-http start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/on-http.service
           └─1983 /usr/bin/node /var/renasar/on-http/index.js

Aug 29 20:24:27 ora systemd[1]: Starting LSB: on-http...
Aug 29 20:24:27 ora on-http[1976]: Starting on-http ...
Aug 29 20:24:27 ora on-http[1976]: on-http started with pid 1983
Aug 29 20:24:27 ora systemd[1]: Started LSB: on-http.
onrack@ora:~$ echo $?
0


When on-http is stopped:
onrack@ora:~$ sudo systemctl status on-http
on-http.service - LSB: on-http
   Loaded: loaded (/etc/init.d/on-http; bad; vendor preset: enabled)
   Active: inactive (dead) since Mon 2016-08-29 20:18:10 UTC; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1881 ExecStop=/etc/init.d/on-http stop (code=exited, status=0/SUCCESS)
  Process: 29340 ExecStart=/etc/init.d/on-http start (code=exited, status=0/SUCCESS)

Aug 29 13:55:13 ora on-http[29340]: Starting on-http ...
Aug 29 13:55:13 ora on-http[29340]: on-http started with pid 29347
Aug 29 13:55:13 ora systemd[1]: Started LSB: on-http.
Aug 29 13:55:13 ora systemd[1]: Started LSB: on-http.
Aug 29 20:18:10 ora systemd[1]: Stopping LSB: on-http...
Aug 29 20:18:10 ora on-http[1881]: Stopping on-http ...
Aug 29 20:18:10 ora on-http[1881]: Killing process 29347
Aug 29 20:18:10 ora on-http[1881]: Removing pid file
Aug 29 20:18:10 ora on-http[1881]: on-http stopped
Aug 29 20:18:10 ora systemd[1]: Stopped LSB: on-http.
onrack@ora:~$ echo $?
3

**Comment by ytjohn** [comment]
`1	program is dead and /var/run pid file exists`   

This is the exit code that has caused salt (config management tool) to assume a process was running, but it was actually dead.

**Comment by ytjohn** [comment]
@jimturnquist It looks like you tested after I added the exit levels in 699357f.

**Comment by jimturnquist** [comment]
Verified John's latest change on onrack appliance.
+1

**Comment by changev** [comment]
test this please

**Comment by jimturnquist** [comment]
What is left for this to be merged?

**Comment by ytjohn** [comment]
All changes are pushed. Let me know if there's anything else preventing these from being merged in.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by ytjohn** [comment]
Added error message suggested by @davidzuhn 

```
root@rackhd01:~# /etc/init.d/on-taskgraph start
Service disabled due to absence of /etc/default/on-taskgraph
root@rackhd01:~# touch /etc/default/on-taskgraph
root@rackhd01:~# /etc/init.d/on-taskgraph start
on-taskgraph already running with pid 30132
```

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by jimturnquist** [comment]
Can we get this one merged?  Is there anything left that is needed?

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
