### PR TITLE
ODR905: add esxSwitchName (in networkDevices) support for ESXi installation

### PR DESCRIPTION
**Pull request by yyscamper**
This is to fix the new issue that recorded in ODR905: https://hwjiraprd01.corp.emc.com/browse/ODR-905

The ESXi installation supports an additional parameter "esxSwitchName" in static network configuration, but the "additionalProperties: false" is set and thus cause the esxSwitchName cannot be specified.

@RackHD/corecommitters @zyoung51 @pengz1 @iceiilin @lanchongyizu

jenkins: depends on https://github.com/RackHD/on-tasks/pull/353

### CODE REVIEW

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by pengz1** [comment]
+1

**Comment by anhou** [comment]
with https://github.com/RackHD/on-tasks/pull/353 merged. 
Jenkins: test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by changev** [comment]
https://github.com/RackHD/on-tasks/pull/353 has been merged, and Jenkins test passed.
so ignore  Jenkins-Dependency-PR  test result which is overdue for this PR.

**Pull request merged**
