### PR TITLE
Set initial graph state to running.

### PR DESCRIPTION
**Pull request by rolandpoulter**
Requires: https://github.com/RackHD/on-core/pull/120

For ODR-593 and https://www.pivotaltracker.com/n/projects/1492888/stories/115448753

### CODE REVIEW

**Comment by benbp** [comment]
CC @jlongever @zyoung51, now we can get rid of the workflow state pending -> running mapping hack :)

**Comment by yyscamper** [comment]
:+1:

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by yyscamper** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by brianparry** [comment]
Merged https://github.com/RackHD/on-core/pull/120, test this please

**Comment by brianparry** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by zyoung51** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by rolandpoulter** [comment]
test this please

**Comment by jlongever** [comment]
+1

**Pull request merged**
