### PR TITLE
RAC-4700

### PR DESCRIPTION
**Pull request by BrentHiggins**
* Fixed 500 error due to bad SEL parsing
* Checks entry.sensorNumber to start with '#' and adds it if missing.
This is because the # is expected and popped of in the code

### CODE REVIEW

**Comment by BrentHiggins** [comment]
@larry-dean @hohene @jimturnquist

**Comment by BrentHiggins** [comment]
@derrickostertag

**Comment by jimturnquist** [comment]
ok to test

**Comment by johren** [comment]
test this please

**Pull request merged**
