### PR TITLE
Add unbound POST /workflows and unit-test

### PR DESCRIPTION
**Pull request by jlongever**
@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya

### CODE REVIEW

**Comment by yyscamper** [comment]
@jlongever ：how the nodeId should be passed for the new API? Always via the workflow's options?

**Comment by jlongever** [comment]
@yyscamper this allows you to run an unbound workfkow. NodeId is not required.

**Comment by yyscamper** [comment]
Thanks for for explanation, @jlongever. Just got meaning of "unbound". So :+1:  for you code.

Meanwhile, I am curious do you have any user case at present?

**Comment by jlongever** [comment]
@yyscamper yes, redfish discovery workflow requires it. https://github.com/RackHD/on-tasks/pull/128

**Comment by anhou** [comment]
:+1:

**Comment by zyoung51** [comment]
+1

**Comment by jlongever** [comment]
Closing.  API added in workflow enhancement PR.

**Pull request closed without merging**
