### PR TITLE
changed reset_type to ResetType to match Redfish standard

### PR DESCRIPTION
**Pull request by alikashmar**
Fix for [RAC-6473](https://rackhd.atlassian.net/browse/RAC-6473)
depends on: https://github.com/RackHD/RackHD/pull/904

### CODE REVIEW

**Comment by keedya** [comment]
@alikashmar  not sure if our system test needs to be updated but I am going to kick the functional test

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- data/views/redfish-1.0/redfish.1.0.0.rackhd.reset.actions.json

**Comment by keedya** [comment]
@dalebremner to review

**Comment by keedya** [comment]
@dalebremner @alikashmar the FIT tests needs to be updated

**Comment by alikashmar** [comment]
@keedya where are the tests located? Are they in another repo?

**Comment by keedya** [comment]
@alikashmar I already submitted a PR and referenced it here

**Comment by keedya** [comment]
@hohene @geoff-reid @dalebremner

**Comment by hohene** [comment]
@BrentHiggins @jimturnquist

**Comment by keedya** [comment]
@jimturnquist  can you review this PR please?

**Pull request merged**
