### PR TITLE
resolve self-inflicted stupidity in editing

### PR DESCRIPTION
**Pull request by heckj**
resolving my self-inflicted editing stupidity - profile wouldn't render with the updates since I didn't balanced the tags correctly, even though it's "commented out" in the iPXE script.

Yes, @heckj is a big dummy.

### CODE REVIEW

**Comment by heckj** [comment]
@RackHD/corecommitters please review my stupidity in all its glory and requisite fix

**Comment by yyscamper** [comment]
+1

**Comment by benbp** [comment]
👍

**Comment by benbp** [comment]
shaaaaaaame :P

**Pull request merged**
