### PR TITLE
[ODR-356] Rename controller_ID to host_ID in smart catalog

### PR DESCRIPTION
**Pull request by WangWinson**
This PR is part of change to fix https://hwjiraprd01.corp.emc.com/browse/ODR-356

The controller ID from get_smart script may vary for different drive connect to the same controller, so leave the controller ID to be defined in northbound API

@RackHD/corecommitters @cgx027 @sunnyqianzhang

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
:+1:

**Comment by WangWinson** [comment]
Dependency PR https://github.com/RackHD/onserve/pull/95
Waiting for it approved and then merge together

**Comment by WangWinson** [comment]
dependency PR merged. So we could merge this PR

**Pull request merged**
