### PR TITLE
Fix Swagger editor error

### PR DESCRIPTION
**Pull request by brianparry**
* Add separate controller for HEAD /templates to keep operationId unique.

### CODE REVIEW

**Comment by brianparry** [comment]
@heckj @geoff-reid

**Comment by heckj** [comment]
👍

**Comment by geoff-reid** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by brianparry** [comment]
test this please

**Pull request merged**
