### PR TITLE
update hound ci config

### PR DESCRIPTION
**Pull request by cgx027**
Issue fix to https://github.com/RackHD/RackHD/issues/391

@RackHD/corecommitters @heckj @yyscamper

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by heckj** [comment]
👍

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
The jenks build can't be related since this file is only read by hound CI, so I'm merging.

**Pull request merged**
