### PR TITLE
Add UUID to HTTP responses

### PR DESCRIPTION
**Pull request by brianparry**
* Add UUID to res.locals and add to error template.
* Log UUID from httpEventMiddleware.

@benbp @yyscamper: As discussed in Slack

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by brianparry** [comment]
test this please

**Pull request merged**
