### PR TITLE
adding slack notifications

### PR DESCRIPTION
**Pull request by tldavies**

### CODE REVIEW

**Comment by tldavies** [comment]
@rolandpoulter @benbp @VulpesArtificem

**Comment by rolandpoulter** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by heckj** [comment]
@tldavies looks like it needs a quick rebase..

**Comment by benbp** [comment]
Heh, sorry :imp:

**Comment by tldavies** [comment]
rebased :-)

**Pull request merged**
