### PR TITLE
Update Redfish schemas to 2016.3

### PR DESCRIPTION
**Pull request by dalebremner**
requires https://github.com/RackHD/RackHD/pull/610

### CODE REVIEW

**Comment by jimturnquist** [comment]
@dalebremner Is the CIT failure noted above fixed with the following:

https://github.com/RackHD/RackHD/pull/610

**Comment by dalebremner** [comment]
jenkins: test this please

**Comment by jimturnquist** [comment]
@dalebremner Just confirming...

The changes in static/DSP8010_1.0.0 were taken wholesale from spmf, correct?

I'm focusing my review on the following:

/data/views/redfish-1.0/redfish.1.0.0.computersystem.1.0.0.json
a/data/views/redfish-1.0/redfish.1.0.0.jsonschemafile.1.0.0.json
a/data/views/redfish-1.0/redfish.1.0.0.processor.1.0.0.json
a/data/views/redfish-1.0/redfish.1.0.0.role.1.0.0.json
a/data/views/redfish-1.0/redfish.1.0.0.thermal.1.0.0.json
a/lib/api/redfish-1.0/account-service.js
a/lib/api/redfish-1.0/chassis.js
a/lib/api/redfish-1.0/event-service.js
a/lib/api/redfish-1.0/managers.js
a/lib/api/redfish-1.0/registry.js
a/lib/api/redfish-1.0/roles.js
a/lib/api/redfish-1.0/schemas.js
a/lib/api/redfish-1.0/service-root.js
a/lib/api/redfish-1.0/session-service.js
a/lib/api/redfish-1.0/systems.js
a/lib/api/redfish-1.0/task-service.js
a/lib/services/redfish-validator-service.js
a/spec/lib/api/redfish-1.0/event-service-spec.js
a/spec/lib/api/redfish-1.0/schemas-spec.js
a/spec/lib/services/schema-api-service-spec.js

**Comment by dalebremner** [comment]
jenkins: test this please

**Comment by dalebremner** [comment]
@jimturnquist Correct. The /static changes are unmodified schemas from DMTF

**Comment by dalebremner** [comment]
Jenkins: test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Pull request merged**
