### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by heckj**
Killing unused file (per  https://github.com/RackHD/on-http/pull/112#discussion_r52050293), and doing some other cleanup since I had a PR already set up. Sorry for the run-around with this @jlmcknight ...

### CODE REVIEW

**Comment by jlmcknight** [comment]
+1

**Comment by benbp** [comment]
@heckj this file has no references anywhere. Perhaps we should just remove it?

**Comment by heckj** [comment]
@benbp if it's no longer in use, then yeah - let's kill it away. I thought it was when I put up this PR. No workflows or responses leveraging the retry.ipxe thing any longer?

**Comment by heckj** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by zyoung51** [comment]
Test this please

**Comment by benbp** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Pull request merged**
