### PR TITLE
Dockerfile changes.

### PR DESCRIPTION
**Pull request by rolandpoulter**
Force copy node_modules, fix exposed ports, and remove file downloads.

Related to: https://github.com/RackHD/RackHD/pull/109

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
Dunno why jenkins on-http tests are blowing up.   Need to check it out. 
+1 either way

**Comment by benbp** [comment]
:+1:

**Comment by anhou** [comment]
:+1:  assume that there isn't any test case is related with docker

**Comment by jlongever** [comment]
jenkins failure unrelated.  +1

**Pull request merged**
