### PR TITLE
[redfish] Session service changes

### PR DESCRIPTION
**Pull request by zyoung51**
- Evaluate privilege of user when processing session logout
- Evaluate privilege of user when processing sessions list and get

### CODE REVIEW

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by changev** [comment]
add to whitelist

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by yyscamper** [comment]
:+1:

**Comment by jlongever** [comment]
+1

**Pull request merged**
