### PR TITLE
change uid to optional

### PR DESCRIPTION
**Pull request by PengTian0**
change uid to optional  for centos and Ubuntu;
and SUSE has supported uid optional, 
EXS don't support uid input.

@yyscamper @iceiilin @panpan0000

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
Jenkins: ok to test

**Comment by anhou** [comment]
:+1:  just let others know that SUSE has support uid optional, and esx don't support uid input

**Comment by yyscamper** [comment]
@anhou :I had the same concern before, @PengTian0 had changed the doc accordingly.

**Pull request merged**
