### PR TITLE
RAC-5253 delete install web ui from zip

### PR DESCRIPTION
**Pull request by changev**
delete the web ui installation  from zip file.

We support 3 ways to install web-ui

1. apt-get install, work with apt-get install rackhd.
2. docker images, work with docker-compose up rackhd
3. if users installed rackhd with src, they should clone web-ui src and build statics manually.

### CODE REVIEW

**Comment by changev** [comment]
test this please

**Comment by panpan0000** [comment]
Can you please elaborate the way #3 ? 
if people run RackHD from src code, and do npm install.
which document can people follow to build/copy on-web-ui.

**Comment by changev** [comment]
@panpan0000 

I'll add some docs in on-http README!

**Comment by panpan0000** [comment]
As what we talk, the concern is 
if people using Node4 to install rackhd from src, but you request them to build on-web-ui by themselves, which requires Node6...

Let's keep -1 👎   until this gets clarified.
@iceiilin

**Pull request closed without merging**
