### PR TITLE
WIP - RAC-5956 baremetal updates - DON'T MERGE ME

### PR DESCRIPTION
**Pull request by hohene**
Added updates into os-install worfklows for ESXi, CentOS and OpenSUSE to help debug install issues we are seeing in the bare-metal regression stack.
The os install workflows fail to 'physical' quanta nodes.

Paired with Manfred on this.

### CODE REVIEW

**Comment by hohene** [comment]
@keedya @manfrednde

**Comment by hohene** [comment]
test this please

**Comment by hohene** [comment]
test this please

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- lib/services/ws-error.js - lib/services/ws-resources.js - lib/services/ws-service.js - package.json - spec/.jshintrc - spec/lib/api/index-spec.js - spec/lib/services/ws-service-spec.js

**Comment by keedya** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- data/templates/centos-ks - data/templates/esx-ks - data/templates/suse-autoinst.xml

**Comment by jimturnquist** [comment]
I checked with @hohene.  This can be closed.

**Pull request closed without merging**
