### PR TITLE
 2.0 API pollers tests occasionally fail #150 

### PR DESCRIPTION
**Pull request by srinia6**
Resolves https://github.com/RackHD/RackHD/issues/150
@brianparry @dalebremner @abildw @geoff-reid @RackHD/corecommitters

### CODE REVIEW

**Comment by srinia6** [comment]
test this please

**Comment by heckj** [comment]
if you see the pull request message to read:

resolves rackhd/rackhd#150

then when this is merged, it will close the github bug

**Comment by heckj** [comment]
:+1:

**Comment by srinia6** [comment]
@heckj - all set now.

**Comment by abildw** [comment]
+1

**Comment by benbp** [comment]
@srinia6 needs to be in the actual description rather than the title I believe.

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
