### PR TITLE
Update readme with taskdoc url and unify the task annotation naming

### PR DESCRIPTION
**Pull request by WangWinson**
- Add /taskdoc url to readme
- Unify naming 'RackHD Task Annotation'

@RackHD/corecommitters @cgx027 @iceiilin @pengz1

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by benbp** [comment]
👍

**Comment by benbp** [comment]
test this please

**Comment by WangWinson** [comment]
Jenkins: test this please

**Pull request merged**
