### PR TITLE
Add file latest and file md5 latest to south API router

### PR DESCRIPTION
**Pull request by WangWinson**
To solve issue #215. 
PR https://github.com/RackHD/on-http/pull/230 has merged to master, and it's also needed for 1.2 release branch

- Add file latest and file md5 latest router to south file router
- Add unit test

@RackHD/corecommitters

### CODE REVIEW

**Comment by yyscamper** [comment]
+1

**Comment by anhou** [comment]
:+1: based on previous master PR review

**Comment by yyscamper** [comment]
test this please

**Comment by WangWinson** [comment]
test this please

**Comment by zyoung51** [comment]
+1, Jenkins failures are due to running master's version of integration tests against the 1.2 release branch and should be ignored.

**Pull request merged**
