### PR TITLE
Generate swagger client python code

### PR DESCRIPTION
**Pull request by jlongever**
- Cleanup apidoc tags
- Run apidoc to swagger converter
- Generate API python library code
- Create debian package scripts

@RackHD/corecommitters @RackHD/rackhd_dev 

synchronous example:
```
from on_http import NodesApi, ApiClient, Configuration

config = Configuration()
config.debug = True
config.verify_ssl = False

client = ApiClient(host='http://localhost:8080',header_name='Content-Type',header_value='application/json')
nodes = NodesApi(api_client=client)
nodes.api1_1_nodes_get()
print client.last_response.data
```

asynchronous example:
```
def cb_func(resp):
    print 'GET /nodes callback!', resp

thread = nodes.api1_1_nodes_get(callback=cb_func)
```

API module list:
```
~/python-client/on_http/apis$ ls -l
catalogs_api.py
config_api.py
files_api.py
lookups_api.py
nodes_api.py
obms_api.py
pollers_api.py
profiles_api.py
schemas_api.py
skus_api.py
tasks_api.py
templates_api.py
versions_api.py
workflows_api.py
workflow_tasks_api.py
```

### CODE REVIEW

**Comment by heckj** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by brianparry** [comment]
:+1:

**Comment by jlongever** [comment]
missed the HWIMO-BUILD script,  needs to be updated....

**Comment by jlongever** [comment]
updated, once checks pass I'll merge.

**Comment by heckj** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
sounds great!

**Pull request merged**
