### PR TITLE
RAC-5235

### PR DESCRIPTION
**Pull request by jimturnquist**
- Replaced usages of waterline.nodes.getNodeById(identifier) with
  nodeApi.getNodeById(identifier)

- Fixed some tabbing/spacing issues

- All system.js get methods that use {identifier} are now properly
  returning 404.

Fixed system spec tests

- nodeApi.getNodeById should not be stubbed out.  waterline.nodes.getNodeById
  should be instead.  This will allow nodeApi.getNodeById to throw any
  exceptions it needs to throw (which are needed in systems.js)

### CODE REVIEW

**Comment by jimturnquist** [comment]
Testing for 404 on bad identifier:

BEFORE:
/Systems/{identifier} failed
/Systems/{identifier}/Processors failed
/Systems/{identifier}/Processors/0 failed
/Systems/{identifier}/SimpleStorage failed
/Systems/{identifier}/SimpleStorage/0 failed
/Systems/{identifier}/Storage failed
/Systems/{identifier}/Storage/{index} failed
/Systems/{identifier}/Storage/{index}/Drives/0 failed
/Systems/{identifier}/Storage/{index}/Volumes failed
/Systems/{identifier}/Storage/{index}/Volumes/0 failed
/Systems/{identifier}/LogServices failed
/Systems/{identifier}/LogServices/sel ok
/Systems/{identifier}/LogServices/sel/Entries ok
/Systems/{identifier}/LogServices/sel/Entries/0 ok
/Systems/{identifier}/SecureBoot failed

AFTER:
/Systems/{identifier} ok
/Systems/{identifier}/Processors ok
/Systems/{identifier}/Processors/0 ok
/Systems/{identifier}/SimpleStorage ok
/Systems/{identifier}/SimpleStorage/0 ok
/Systems/{identifier}/Storage ok
/Systems/{identifier}/Storage/{index} ok
/Systems/{identifier}/Storage/{index}/Drives/0 ok
/Systems/{identifier}/Storage/{index}/Volumes ok
/Systems/{identifier}/Storage/{index}/Volumes/0 ok
/Systems/{identifier}/LogServices ok
/Systems/{identifier}/LogServices/sel ok
/Systems/{identifier}/LogServices/sel/Entries ok
/Systems/{identifier}/LogServices/sel/Entries/0 ok
/Systems/{identifier}/SecureBoot ok

**Comment by jimturnquist** [comment]
Coverage results went down slightly in this change since system.js operations now fail early (as they are supposed to).  system-spec.js does not stub out nodeApi.getNodeById which actually increased coverage in the nodeApi code.

**Comment by jimturnquist** [comment]
Also fixes:

https://rackhd.atlassian.net/browse/RAC-5238

**Comment by jimturnquist** [comment]
Test this please.

**Comment by BrentHiggins** [comment]
+1

**Pull request merged**
