### PR TITLE
Redact encrypted fields in OBM and SNMP serializer

### PR DESCRIPTION
**Pull request by geoff-reid**
@srinia6 @dalebremner @abildw @RackHD/corecommitters

### CODE REVIEW

**Comment by abildw** [comment]
+1

**Comment by heckj** [comment]
@geoff-reid I thought there was somewhere that we were doing auto-redaction in middleware... never mind, I was wrong, but so you're aware of it - here's what we did for redacting this kind of information from the event logs. https://github.com/RackHD/on-core/blob/master/lib/serializables/log-event.js#L144-L162

I don't know if you'd want to follow that pattern of having what values you explicitly redact in constants or not. The "serializables" construct was something Frey set up ages ago, but was never applied to any of the HTTP endpoints, so it may not be worth the trouble, especially as we get into the swagger and redfish spaces.

**Comment by benbp** [comment]
:+1:

**Comment by yyscamper** [comment]
I think we should move the Redact functionality to a common service in on-core, neither like our current design in LogEvent nor implement a brand new one in on-http, so that it can be shared.

**Comment by brianparry** [comment]
@yyscamper: While I think a common mechanism for redacting passwords is a good idea, it's outside the scope of this PR.  The idea here is to implement redaction for OBMs as quickly as possible to eliminate the possibility of revealing passwords.  I'd suggest we open a new google groups thread to discuss a more general solution.

@geoff-reid  :+1:

**Comment by brianparry** [comment]
@yyscamper Looks like the pollers route also has passwords that should be redacted: https://github.com/RackHD/on-http/pull/134.

**Pull request merged**
