### PR TITLE
Changes to 2.0 pollers/data route

### PR DESCRIPTION
**Pull request by brianparry**
* Check if poller exists and return 404 if it does not.
* Collapse getPollersByIdDataCurrent into getPollersByIdData.

@RackHD/corecommitters @srinia6 @dalebremner @BillyAbildgaard @keedya @jlongever

### CODE REVIEW

**Comment by keedya** [comment]
:+1:

**Comment by brianparry** [comment]
Depends on: https://github.com/RackHD/on-tasks/pull/308

**Comment by srinia6** [comment]
+1

**Comment by benbp** [comment]
👍

**Comment by brianparry** [comment]
Merging without passing tests to get CI tests running again.  Tests should pass once https://github.com/RackHD/RackHD/pull/366 is merged.

**Comment by brianparry** [comment]
test this please

**Pull request merged**
