### PR TITLE
on-http code

### PR DESCRIPTION
**Pull request by longhornteam35**
on-http code additions. Includes redfish handlers and computer system,
drive, storage, storage collection, volume, and volume collection
views.

### CODE REVIEW

**Comment by rahmanmuhamad** [comment]
Please look into houndCI comments and solve as many you can

**Comment by dalebremner** [comment]
Would be good to add unit tests to correct coverage drop.

**Comment by rahmanmuhamad** [comment]
I should be able to fix these comments after merge , currently don't have to repo for changes

**Comment by rahmanmuhamad** [comment]
This PR has conflict and need to be resolved before we can merge

**Pull request merged**
