### PR TITLE
Feature/files md5 remastering

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
updating 2.0/files/{filename}/md5 so it returns a string to be consistent with 1.1 api

@RackHD/corecommitters @dalebremner @geoff-reid @srinia6 @zyoung51

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by amymullins** [comment]
resolves RackHD/on-tasks#351

**Comment by BillyAbildgaard** [comment]
@amymullins this one only partially resolves that.  I still have another PR in on-tasks I need to put up before it's fully resolved

**Comment by amymullins** [comment]
@BillyAbildgaard , i'll delete my comment so it won't automatically close out the issue.

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
