### PR TITLE
Fix null check for node.sku in sku service setupScope

### PR DESCRIPTION
**Pull request by benbp**
Resolves https://github.com/RackHD/RackHD/issues/128

@RackHD/corecommitters

### CODE REVIEW

**Comment by zyoung51** [comment]
+1

**Comment by benbp** [comment]
test this please

**Comment by benbp** [comment]
test this please

**Comment by heckj** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by zyoung51** [comment]
test this please

**Comment by benbp** [comment]
Requires https://github.com/RackHD/on-http/pull/177

**Comment by zyoung51** [comment]
@RackHD/corecommitters at +3 but coveralls is out to lunch.  Can this be merged?

**Pull request merged**
