### PR TITLE
ConfigureSelf privilege should only permit a user to change their pas…

### PR DESCRIPTION
**Pull request by zyoung51**
…sword

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by brianparry** [comment]
:+1:

**Comment by brianparry** [comment]
test this plesae

**Comment by yyscamper** [comment]
:+1:

**Comment by changev** [comment]
test this plesae

**Comment by changev** [comment]
test this please

**Comment by amymullins** [comment]
test this please

**Pull request merged**
