### PR TITLE
enabling running CoreOS

### PR DESCRIPTION
**Pull request by heckj**
- install not working in vagrant demo, so switching that PXE setup to only boot/run CoreOS while I sort out the specifics

### CODE REVIEW

**Comment by heckj** [comment]
will be re-enabling, but need to sort out how to mirror CoreOS stable channel information locally for the demo. Installation process is failing because VM in vagrant setup doesn't have access to pull the stock image from the internet

**Comment by rolandpoulter** [comment]
:+1:

**Comment by heckj** [comment]
Walking to the bus, I thought of two paths for making the full "install" demo work 

1. use the -b option with coreos_install and have a mirror or relevant files on the RackHD host, maybe leveraging the /coreos/ directory structure that's already there and just lightly expand it

2. for the Vagrant demo setup, add in IP forwarding and set the RackHD server (which does have access to the internet) as the default gateway with DHCP so that files can be retrieved remotely - will also need to shim in some DNS - something like Google's 8.8.8.8 as a default would likely work.

I think the 1st may be faster, and leverage to work in the future with the proxy mechanisms we'll be adding

**Comment by heckj** [comment]
Updated PR to optimize the install flow to pull from a mirror installed onto RackHD - at least until we can more formally update this to utilize a proxy mechanism from RackHD to the internet to pull files as needed. Related PR exists in https://github.com/RackHD/RackHD/pull/14 that puts relevant files into the
right place on a demo setup.

Added annotations/comments into the profile (ipxe script) for future reference on how that flow works and where to go for options when/if additional debugging it needed.

**Comment by benbp** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Pull request merged**
