### PR TITLE
Chassis by serial number

### PR DESCRIPTION
**Pull request by zyoung51**
Add URIs to GET chassis by serial number in addition to node id

@RackHD/corecommitters @uppalk1 @keedya @tannoa2

### CODE REVIEW

**Comment by zyoung51** [comment]
test this please

**Comment by benbp** [comment]
:+1:

**Comment by heckj** [comment]
:+1:

**Comment by benbp** [comment]
Waiting on results from https://travis-ci.org/RackHD/on-http/builds/107101409 then I'll merge.

**Comment by heckj** [comment]
@benbp underlying breakage due to json-faker library resolved with an update to un-break it - 0.10 build passed, I just re-kicked the node4 build

**Comment by benbp** [comment]
kk, let me know and i'll merge.

**Comment by zyoung51** [comment]
@benbp can this be merged?

**Comment by jlongever** [comment]
+1 merging...

**Pull request merged**
