### PR TITLE
removed refs to onRack

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@heckj @benbp 

Please do not merge this is blocked.

### CODE REVIEW

**Comment by jlongever** [comment]
+1

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
@DavidjohnBlodgett could you mention blocked on what?

**Comment by DavidjohnBlodgett** [comment]
@benbp @jlongever sorry about being MIA there... so this and afew other PRs I posted, should be held back until my on-core PR is merged~ I'll update the PRs with this info... and I have the on-core PR updated and rerunning tests now!

**Comment by DavidjohnBlodgett** [comment]
Blocked by https://github.com/RackHD/on-core/pull/69

**Comment by DavidjohnBlodgett** [comment]
@benbp @jlongever this is now unblocked.

**Comment by benbp** [comment]
@derrickostertag FYI

**Pull request merged**
