### PR TITLE
Add query by type back to API GET /nodes

### PR DESCRIPTION
**Pull request by keedya**
@RackHD/corecommitters @hohene @amymullins @srinia6 @BillyAbildgaard

### CODE REVIEW

**Comment by srinia6** [comment]
+1

**Comment by zyoung51** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by keedya** [comment]
test this please

**Comment by yyscamper** [comment]
For this PR, my thought is :+1: 

But I want to mention that we had a discussion about how to make the resource query be more generic: https://groups.google.com/forum/#!searchin/rackhd/query%7Csort:relevance/rackhd/hnGc9rHMi74/NpF5jGnjAwAJ

**Comment by hohene** [comment]
@yyscamper Following the discussion you pointed at above, there isn't a resolution as how to proceed from what I can tell, did any of it get implemented?  We have to make sure to stay backwards compatible for /api/1.1/ commands as we have released products that rely on them.  /api/2.0 commands are fine to change.  Not sure where to post this comment...so put it here.

**Pull request merged**
