### PR TITLE
Search environment key with 'config.' for graph definition.

### PR DESCRIPTION
**Pull request by cgx027**
Search environment key with 'config.' for graph definition.

This is a similar change as done in https://github.com/RackHD/on-tasks/blob/master/lib/utils/job-utils/workflow-tool.js#L66

### CODE REVIEW

**Comment by yyscamper** [comment]
@RackHD/corecommitters @zyoung51

**Comment by anhou** [comment]
:+1:

**Comment by panpan0000** [comment]
test this please

**Comment by cgx027** [comment]
test this please

**Comment by cgx027** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
