### PR TITLE
return empty object when access api without token or with error token

### PR DESCRIPTION
**Pull request by PengTian0**
I tried to access API  without token or with a wrong token and just got an empty object.
Cause:
The returned info object is a list.
But the code uses it as a dictionary which contains "message".

### CODE REVIEW

**Comment by iceiilin** [comment]
:+1:

**Comment by PengTian0** [comment]
@cgx027 @yyscamper @anhou @panpan0000

**Comment by lanchongyizu** [comment]
:+1: after fix houndci problems.

**Comment by PengTian0** [comment]
Jenkins: test this please

**Pull request merged**
