### PR TITLE
Redfish SerialInterface GET APIs

### PR DESCRIPTION
**Pull request by srinia6**
Add implementation to SerialInterfaceCollection and SerialInterface routes. 

@RackHD/corecommitters

### CODE REVIEW

**Comment by srinia6** [comment]
Test this please

**Comment by srinia6** [comment]
Jenkins: depends on https://github.com/RackHD/RackHD/pull/832

**Comment by srinia6** [comment]
test this please

**Comment by srinia6** [comment]
@changev Can you please look at the dependency Jenkins job? It is looking for incorrect PR url - http://rackhdci.lss.emc.com/blue/organizations/jenkins/RackHD/detail/RackHD/569/pipeline/

**Comment by geoff-reid** [comment]
test this please

**Comment by srinia6** [comment]
Jenkins: depends on https://github.com/RackHD/RackHD/pull/832

**Comment by geoff-reid** [comment]
Merging singe Jenkins and Unit tests passed at part of PR https://github.com/RackHD/RackHD/pull/832
The dependency is not working for rackhd repo.

**Pull request merged**
