### PR TITLE
Create linux diag profile

### PR DESCRIPTION
**Pull request by jlongever**
Added Linux diag boot profile for EMC diagnostic images.

@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya

### CODE REVIEW

**Comment by benbp** [comment]
👍

**Comment by benbp** [comment]
Would the profile name be clearer if it was just like "boot-initrd" or something?

**Comment by jlongever** [comment]
Probably,  or `linux-generic.ipxe` ?  The diag image booting can take special `bootargs` which is just a string of `mem=<map>` and other parameters,  so I guess the name could be generic.

**Comment by jlongever** [comment]
@benbp renamed it to `linux-generic.ipxe`

**Comment by anhou** [comment]
@jlongever  A minor comment at https://github.com/RackHD/on-http/pull/345

**Comment by jlongever** [comment]
@anhou This follows the same pattern as `linux.ipxe`.  Are you suggesting there is a design issue here? Is this a gating issue for you?

**Pull request merged**
