### PR TITLE
fixing ipv6 gateway

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
@tannoa2 @srinia6 @dalebremner @geoff-reid @keedya

### CODE REVIEW

**Comment by cgx027** [comment]
:+1:  Good finding.

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by BillyAbildgaard** [comment]
test this please

**Pull request merged**
