### PR TITLE
Add bintray link to readme

### PR DESCRIPTION
**Pull request by brianparry**
@RackHD/corecommitters

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by keedya** [comment]
:+1:

**Comment by geoff-reid** [comment]
:+1:

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by brianparry** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Pull request merged**
