### PR TITLE
'Allowing for systems with more than 26 drives'

### PR DESCRIPTION
**Pull request by ytjohn**
With this line changed, we can get drives that have /dev/sdaa and beyond.

### CODE REVIEW

**Comment by ytjohn** [comment]
```
[
    {
        "devName": "sdag",
        "esxiWwid": "naa.5000cca23bda0791",
        "identifier": 0,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHV835X",
        "scsiId": "0:0:33:0"
    },
    {
        "devName": "sdax",
        "esxiWwid": "naa.5000cca23bda3ee3",
        "identifier": 1,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHVRV0X",
        "scsiId": "0:0:50:0"
    },
    {
        "devName": "sdaj",
        "esxiWwid": "naa.5000cca23bda4f23",
        "identifier": 2,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHVW56X",
        "scsiId": "0:0:36:0"
    },
    {
        "devName": "sdaq",
        "esxiWwid": "naa.5000cca23bda6108",
        "identifier": 3,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHW0XZX",
        "scsiId": "0:0:43:0"
    },
    {
        "devName": "sdad",
        "esxiWwid": "naa.5000cca23bda6ac3",
        "identifier": 4,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHW3JAX",
        "scsiId": "0:0:29:0"
    },
    {
        "devName": "sdu",
        "esxiWwid": "naa.5000cca23bda6fe0",
        "identifier": 5,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHW4WKX",
        "scsiId": "0:0:20:0"
    },
    {
        "devName": "sdak",
        "esxiWwid": "naa.5000cca23bda8506",
        "identifier": 6,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWAJ6X",
        "scsiId": "0:0:37:0"
    },
    {
        "devName": "sdn",
        "esxiWwid": "naa.5000cca23bda893a",
        "identifier": 7,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWBMXX",
        "scsiId": "0:0:13:0"
    },
    {
        "devName": "sdg",
        "esxiWwid": "naa.5000cca23bda8b1f",
        "identifier": 8,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWD4KX",
        "scsiId": "0:0:6:0"
    },
    {
        "devName": "sds",
        "esxiWwid": "naa.5000cca23bdaadda",
        "identifier": 9,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWPDBX",
        "scsiId": "0:0:18:0"
    },
    {
        "devName": "sdbg",
        "esxiWwid": "naa.5000cca23bdab09d",
        "identifier": 10,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWR45X",
        "scsiId": "0:0:59:0"
    },
    {
        "devName": "sdi",
        "esxiWwid": "naa.5000cca23bdab0d2",
        "identifier": 11,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWR5WX",
        "scsiId": "0:0:8:0"
    },
    {
        "devName": "sdz",
        "esxiWwid": "naa.5000cca23bdabd6b",
        "identifier": 12,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWUJXX",
        "scsiId": "0:0:25:0"
    },
    {
        "devName": "sdo",
        "esxiWwid": "naa.5000cca23bdabed5",
        "identifier": 13,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWUXLX",
        "scsiId": "0:0:14:0"
    },
    {
        "devName": "sdan",
        "esxiWwid": "naa.5000cca23bdac0ae",
        "identifier": 14,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWVDVX",
        "scsiId": "0:0:40:0"
    },
    {
        "devName": "sdq",
        "esxiWwid": "naa.5000cca23bdac58a",
        "identifier": 15,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWWPZX",
        "scsiId": "0:0:16:0"
    },
    {
        "devName": "sdbf",
        "esxiWwid": "naa.5000cca23bdac87d",
        "identifier": 16,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWXHAX",
        "scsiId": "0:0:58:0"
    },
    {
        "devName": "sdd",
        "esxiWwid": "naa.5000cca23bdaca56",
        "identifier": 17,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWXZLX",
        "scsiId": "0:0:3:0"
    },
    {
        "devName": "sdk",
        "esxiWwid": "naa.5000cca23bdacf4b",
        "identifier": 18,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWZ9JX",
        "scsiId": "0:0:10:0"
    },
    {
        "devName": "sdy",
        "esxiWwid": "naa.5000cca23bdad0d4",
        "identifier": 19,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHWZR6X",
        "scsiId": "0:0:24:0"
    },
    {
        "devName": "sdv",
        "esxiWwid": "naa.5000cca23bdad434",
        "identifier": 20,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX0M2X",
        "scsiId": "0:0:21:0"
    },
    {
        "devName": "sdaa",
        "esxiWwid": "naa.5000cca23bdad45b",
        "identifier": 21,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX0NAX",
        "scsiId": "0:0:26:0"
    },
    {
        "devName": "sdx",
        "esxiWwid": "naa.5000cca23bdad4f9",
        "identifier": 22,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX0UEX",
        "scsiId": "0:0:23:0"
    },
    {
        "devName": "sdm",
        "esxiWwid": "naa.5000cca23bdad833",
        "identifier": 23,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX1P2X",
        "scsiId": "0:0:12:0"
    },
    {
        "devName": "sdf",
        "esxiWwid": "naa.5000cca23bdadcb8",
        "identifier": 24,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX2WDX",
        "scsiId": "0:0:5:0"
    },
    {
        "devName": "sdat",
        "esxiWwid": "naa.5000cca23bdadf97",
        "identifier": 25,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX3N3X",
        "scsiId": "0:0:46:0"
    },
    {
        "devName": "sdaf",
        "esxiWwid": "naa.5000cca23bdae133",
        "identifier": 26,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX42DX",
        "scsiId": "0:0:31:0"
    },
    {
        "devName": "sde",
        "esxiWwid": "naa.5000cca23bdae70f",
        "identifier": 27,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX5MTX",
        "scsiId": "0:0:4:0"
    },
    {
        "devName": "sdw",
        "esxiWwid": "naa.5000cca23bdae8d8",
        "identifier": 28,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX63JX",
        "scsiId": "0:0:22:0"
    },
    {
        "devName": "sdbh",
        "esxiWwid": "naa.5000cca23bdaede3",
        "identifier": 29,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX7G5X",
        "scsiId": "0:0:60:0"
    },
    {
        "devName": "sdba",
        "esxiWwid": "naa.5000cca23bdaf473",
        "identifier": 30,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHX96BX",
        "scsiId": "0:0:53:0"
    },
    {
        "devName": "sdr",
        "esxiWwid": "naa.5000cca23bdaf7cb",
        "identifier": 31,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXA2ZX",
        "scsiId": "0:0:17:0"
    },
    {
        "devName": "sdah",
        "esxiWwid": "naa.5000cca23bdafc46",
        "identifier": 32,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXB8ZX",
        "scsiId": "0:0:34:0"
    },
    {
        "devName": "sdbj",
        "esxiWwid": "naa.5000cca23bdafe04",
        "identifier": 33,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXBSBX",
        "scsiId": "0:0:62:0"
    },
    {
        "devName": "sdac",
        "esxiWwid": "naa.5000cca23bdafe4f",
        "identifier": 34,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXBUTX",
        "scsiId": "0:0:28:0"
    },
    {
        "devName": "sdai",
        "esxiWwid": "naa.5000cca23bdb008f",
        "identifier": 35,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXDEBX",
        "scsiId": "0:0:35:0"
    },
    {
        "devName": "sdao",
        "esxiWwid": "naa.5000cca23bdb055a",
        "identifier": 36,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXEPYX",
        "scsiId": "0:0:41:0"
    },
    {
        "devName": "sdab",
        "esxiWwid": "naa.5000cca23bdb0658",
        "identifier": 37,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXEZ4X",
        "scsiId": "0:0:27:0"
    },
    {
        "devName": "sday",
        "esxiWwid": "naa.5000cca23bdb06bd",
        "identifier": 38,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXG2DX",
        "scsiId": "0:0:51:0"
    },
    {
        "devName": "sdaz",
        "esxiWwid": "naa.5000cca23bdb0be6",
        "identifier": 39,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXHG0X",
        "scsiId": "0:0:52:0"
    },
    {
        "devName": "sdaw",
        "esxiWwid": "naa.5000cca23bdb1556",
        "identifier": 40,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXKYYX",
        "scsiId": "0:0:49:0"
    },
    {
        "devName": "sdbb",
        "esxiWwid": "naa.5000cca23bdb166c",
        "identifier": 41,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXL7XX",
        "scsiId": "0:0:54:0"
    },
    {
        "devName": "sdj",
        "esxiWwid": "naa.5000cca23bdb1aca",
        "identifier": 42,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXMDZX",
        "scsiId": "0:0:9:0"
    },
    {
        "devName": "sdap",
        "esxiWwid": "naa.5000cca23bdb202f",
        "identifier": 43,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXNVJX",
        "scsiId": "0:0:42:0"
    },
    {
        "devName": "sdav",
        "esxiWwid": "naa.5000cca23bdb22a0",
        "identifier": 44,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXPHPX",
        "scsiId": "0:0:48:0"
    },
    {
        "devName": "sdh",
        "esxiWwid": "naa.5000cca23bdb3160",
        "identifier": 45,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXUEHX",
        "scsiId": "0:0:7:0"
    },
    {
        "devName": "sdbd",
        "esxiWwid": "naa.5000cca23bdb35e4",
        "identifier": 46,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXVMTX",
        "scsiId": "0:0:56:0"
    },
    {
        "devName": "sdal",
        "esxiWwid": "naa.5000cca23bdb44c9",
        "identifier": 47,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHXZLTX",
        "scsiId": "0:0:38:0"
    },
    {
        "devName": "sdau",
        "esxiWwid": "naa.5000cca23bdb5299",
        "identifier": 48,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY38VX",
        "scsiId": "0:0:47:0"
    },
    {
        "devName": "sdae",
        "esxiWwid": "naa.5000cca23bdb52c7",
        "identifier": 49,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY3AAX",
        "scsiId": "0:0:30:0"
    },
    {
        "devName": "sdt",
        "esxiWwid": "naa.5000cca23bdb5758",
        "identifier": 50,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY4K1X",
        "scsiId": "0:0:19:0"
    },
    {
        "devName": "sdas",
        "esxiWwid": "naa.5000cca23bdb5f62",
        "identifier": 51,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY6PEX",
        "scsiId": "0:0:45:0"
    },
    {
        "devName": "sdc",
        "esxiWwid": "naa.5000cca23bdb631a",
        "identifier": 52,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY7P4X",
        "scsiId": "0:0:2:0"
    },
    {
        "devName": "sdbi",
        "esxiWwid": "naa.5000cca23bdb63ad",
        "identifier": 53,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY7UWX",
        "scsiId": "0:0:61:0"
    },
    {
        "devName": "sdl",
        "esxiWwid": "naa.5000cca23bdb649b",
        "identifier": 54,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY82KX",
        "scsiId": "0:0:11:0"
    },
    {
        "devName": "sdbe",
        "esxiWwid": "naa.5000cca23bdb6673",
        "identifier": 55,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY8KTX",
        "scsiId": "0:0:57:0"
    },
    {
        "devName": "sdbc",
        "esxiWwid": "naa.5000cca23bdb6ad1",
        "identifier": 56,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY9RVX",
        "scsiId": "0:0:55:0"
    },
    {
        "devName": "sdp",
        "esxiWwid": "naa.5000cca23bdb6b26",
        "identifier": 57,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHY9ULX",
        "scsiId": "0:0:15:0"
    },
    {
        "devName": "sdar",
        "esxiWwid": "naa.5000cca23bdb7371",
        "identifier": 58,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHYD12X",
        "scsiId": "0:0:44:0"
    },
    {
        "devName": "sdam",
        "esxiWwid": "naa.5000cca23bdbab1a",
        "identifier": 59,
        "linuxWwid": "/dev/disk/by-id/ata-HUH728080ALN600_2EHYVVRX",
        "scsiId": "0:0:39:0"
    },
    {
        "devName": "sda",
        "esxiWwid": "t10.ATA_____SATADOM2DSL_3ME______________________________________________",
        "identifier": 60,
        "linuxWwid": "/dev/disk/by-id/ata-SATADOM-SL_3ME_20151216AAAA00000292",
        "scsiId": "2:0:0:0",
        "virtualDisk": ""
    },
    {
        "devName": "sdb",
        "esxiWwid": "naa.5000cca04dab3ca8",
        "identifier": 61,
        "linuxWwid": "/dev/disk/by-id/scsi-35000cca04dab3ca8",
        "scsiId": "0:0:0:0"
    }
]

```

**Comment by ytjohn** [comment]
Stand by a moment. I had a failure creating the driveid catalog on one of my nodes, so I'm retesting.

**Comment by pengz1** [comment]
@ytjohn 
Please change the RE to:
/sd[a-z]$|sd[a-z][a-z]$|hd[a-z]$|hd[a-z][a-z]$/i

**Comment by ytjohn** [comment]
@pengz1 regex updated.

**Comment by pengz1** [comment]
+1

**Pull request merged**
