### PR TITLE
RAC-4701 - SEL event date translation error from poller data to redfish

### PR DESCRIPTION
**Pull request by BrentHiggins**
* Month is zero indexed by moment so we had to decrement it

### CODE REVIEW

**Comment by BrentHiggins** [comment]
@stuart-stanley @hohene @larry-dean @johren

**Comment by larry-dean** [comment]
test this please

**Comment by stuart-stanley** [comment]
Note: I'm trying to track down why the PR-gate isn't being triggered on this.

**Comment by stuart-stanley** [comment]
test this please

**Comment by larry-dean** [comment]
test this please

**Comment by BrentHiggins** [comment]
test this please

**Pull request merged**
