### PR TITLE
Fixed bug: a node can be containedBy two rack

### PR DESCRIPTION
**Pull request by VulpesArtificem**
fix for https://hwjiraprd01.corp.emc.com/browse/ODR-882 
and https://hwjiraprd01.corp.emc.com/browse/ODR-885

@RackHD/corecommitters

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by pscharla** [comment]
@RackHD/corecommitters Please review when available. This is *NOT* blocking a P1 ODR, but some nice to have fixes.

**Comment by pscharla** [comment]
@RackHD/corecommitters Please review these changes to close out this work.

**Comment by anhou** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
👍

**Pull request merged**
