### PR TITLE
Config route for 2.0 API

### PR DESCRIPTION
**Pull request by geoff-reid**
Add route and unit test for 2.0 config route
@brianparry @abildw @dalebremner @srinia6

### CODE REVIEW

**Comment by geoff-reid** [comment]
Fixed hound violations.

**Comment by geoff-reid** [comment]
test this please

**Comment by brianparry** [comment]
@RackHD/corecommitters

**Comment by brianparry** [comment]
:+1:

**Comment by dalebremner** [comment]
:+1:

**Comment by srinia6** [comment]
+1

**Comment by abildw** [comment]
:+1:

**Pull request merged**
