### PR TITLE
prevent app.listen() from completing before swagger is ready

### PR DESCRIPTION
**Pull request by geoff-reid**
@brianparry @jlongever @dalebremner @abildw @srinia6

### CODE REVIEW

**Comment by heckj** [comment]
:+1: 

Joys of a callback heavy language :-)

**Comment by dalebremner** [comment]
:+1: 
Works awesome!!!

**Comment by brianparry** [comment]
:+1:

**Comment by jlongever** [comment]
@zyoung51's PR already resolved this by using promisfy().  https://github.com/RackHD/on-http/pull/99/files#diff-9c7deffd71e2db721d0aa18017844613R158

**Comment by abildw** [comment]
:+1: 

:)

**Pull request merged**
