### PR TITLE
Remove sudo and package dependencies from travis file (so we can have…

### PR DESCRIPTION
**Pull request by benbp**
… travis containers)

Our unit tests here shouldn't require sudo or apt updates, so remove them in order to support new travis containerized infrastructure.

### CODE REVIEW

**Comment by heckj** [comment]
+1

**Comment by benbp** [comment]
@tldavies @VulpesArtificem

**Comment by tldavies** [comment]
+1

**Comment by rolandpoulter** [comment]
@benbp We may need to put this back for node v4 support. See https://github.com/RackHD/on-core/blob/master/.travis.yml#L19

**Comment by benbp** [comment]
Ah ok, I'll see if I can just disable gs-stats in these unit tests preferably.

**Comment by rolandpoulter** [comment]
Need to change on-core to not install `gs-stats`, otherwise builds will break during install step.

**Pull request merged**
