### PR TITLE
ODR-825: RackHD Redfish API - GET /Chassis/{identifier}/Thermal - 0 a…

### PR DESCRIPTION
**Pull request by jlongever**
…nd empty string false in javascript
- https://www.pivotaltracker.com/story/show/128150499

@zyoung51 @RackHD/corecommitters

### CODE REVIEW

**Comment by heckj** [comment]
👍

**Comment by anhou** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Comment by srinia6** [comment]
+1

**Pull request merged**
