### PR TITLE
Add scoped profile (skupack) support to the profile rendering path

### PR DESCRIPTION
**Pull request by zyoung51**
@RackHD/corecommitters @uppalk1 @keedya @tannoa2

### CODE REVIEW

**Comment by zyoung51** [comment]
Depends on: https://github.com/RackHD/on-core/pull/84
@RackHD/corecommitters @uppalk1 @keedya @tannoa2

**Comment by yyscamper** [comment]
:+1:

**Comment by benbp** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Pull request merged**
