### PR TITLE
Issue #381 - add HEAD meathod to the 2.0 templates route.

### PR DESCRIPTION
**Pull request by geoff-reid**
Fix for RackHD Issue [RackHD/RackHD#381](https://github.com/RackHD/RackHD/issues/381  
)

@brianparry @BillyAbildgaard @keedya @dalebremner @srinia6 @RackHD/corecommitters

### CODE REVIEW

**Comment by anhou** [comment]
I guess you're resolving resolves https://github.com/RackHD/RackHD/issues/381 not on-http's 381 :)

**Comment by anhou** [comment]
:+1:

**Comment by geoff-reid** [comment]
Yes, this is for RackHD/RackHD#381(https://github.com/RackHD/RackHD/issues/381), I've updated the comment above with the correct link.

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
