### PR TITLE
Fix for switch auto-discovery

### PR DESCRIPTION
**Pull request by dalebremner**
- Add IBM settings to node schema
- Change autoDiscover property from string to boolean

### CODE REVIEW

**Comment by dalebremner** [comment]
Jenkins: depends on https://github.com/RackHD/RackHD/pull/734

**Comment by dalebremner** [comment]
Jenkins: test this please

**Comment by brianparry** [comment]
@dalebremner I think there are some docs changes associated with this as well.

**Comment by dalebremner** [comment]
https://rackhd.atlassian.net/browse/RAC-4731

**Pull request merged**
